# Generated by Django 5.2.1 on 2025-06-04 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave",
            fields=[
                ("idleave", models.AutoField(primary_key=True, serialize=False)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual"),
                            ("AUTHORIZED", "Authorized Absence"),
                            ("SICK", "Sick"),
                            ("PATERNITY", "Paternity"),
                            ("MATERNITY", "Maternity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("duration", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
