# Generated by Django 5.2.1 on 2025-06-04 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="username",
        ),
    ]
