# Generated by Django 5.2.1 on 2025-05-27 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0006_remove_employee_email"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authentication",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="authentication",
            name="idemployee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendance.employee",
            ),
        ),
        migrations.AlterField(
            model_name="authentication",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="authentication",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("employee", "Employé")],
                default="employee",
                max_length=20,
            ),
        ),
    ]
