# Generated by Django 5.1.7 on 2025-04-18 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0004_alter_department_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["name"],
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="attendance.employee",
            ),
        ),
    ]
