# Generated by Django 5.1.7 on 2025-04-19 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "attendance",
            "0005_alter_attendance_options_alter_department_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
    ]
